import { GithubConfig, RiskReportItem } from "../types";

const BASE_URL = "https://api.github.com";

export const verifyRepoAccess = async (config: GithubConfig): Promise<boolean> => {
  try {
    const response = await fetch(`${BASE_URL}/repos/${config.owner}/${config.repo}`, {
      headers: {
        Authorization: `Bearer ${config.token}`,
        Accept: "application/vnd.github.v3+json",
      },
    });
    return response.ok;
  } catch (error) {
    console.error("GitHub verification failed", error);
    return false;
  }
};

export const publishReportToGithub = async (
  config: GithubConfig,
  reports: RiskReportItem[]
): Promise<string> => {
  const dateStr = new Date().toISOString().split('T')[0];
  // Default path if not specified, ensuring it ends with .md
  let path = config.path || `audit-risks/risk-register-${dateStr}.md`;
  if (!path.endsWith('.md')) path += '.md';

  // Generate Markdown Content
  let fileContent = `# Emerging Risk Register - ${dateStr}\n\n`;
  fileContent += `Generated by AuditScout AI on ${new Date().toLocaleString()}\n\n`;

  reports.forEach((report) => {
    fileContent += `## ${report.timeFrame}\n`;
    fileContent += `${report.content}\n\n`;
    
    if (report.sources && report.sources.length > 0) {
      fileContent += `**Sources:**\n`;
      report.sources.forEach((chunk) => {
        if (chunk.web) {
          fileContent += `- [${chunk.web.title}](${chunk.web.uri})\n`;
        }
      });
    }
    fileContent += `\n---\n\n`;
  });

  // Base64 encode content (handles UTF-8)
  const contentEncoded = btoa(unescape(encodeURIComponent(fileContent)));

  // Check if file exists to get SHA (needed for update)
  let sha: string | undefined;
  try {
    const checkRes = await fetch(`${BASE_URL}/repos/${config.owner}/${config.repo}/contents/${path}`, {
      headers: {
        Authorization: `Bearer ${config.token}`,
        Accept: "application/vnd.github.v3+json",
      },
    });
    if (checkRes.ok) {
      const data = await checkRes.json();
      sha = data.sha;
    }
  } catch (e) {
    // File doesn't exist, that's fine
  }

  // Create or Update file
  const body: any = {
    message: `AuditScout: Risk Register Update ${dateStr}`,
    content: contentEncoded,
  };
  if (sha) {
    body.sha = sha;
  }

  const response = await fetch(`${BASE_URL}/repos/${config.owner}/${config.repo}/contents/${path}`, {
    method: "PUT",
    headers: {
      Authorization: `Bearer ${config.token}`,
      Accept: "application/vnd.github.v3+json",
      "Content-Type": "application/json",
    },
    body: JSON.stringify(body),
  });

  if (!response.ok) {
    const errorData = await response.json();
    throw new Error(errorData.message || "Failed to publish to GitHub");
  }

  const responseData = await response.json();
  return responseData.content.html_url;
};