import { GoogleGenAI } from "@google/genai";
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

// Setup paths for ESM
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Configuration
const API_KEY = process.env.API_KEY;
const MODEL_NAME = "gemini-2.5-flash";
const REPORT_DIR = path.join(__dirname, '../reports');

// Timeframes to scan
const TIME_FRAMES = [
  'Past Day',
  'Past Week',
  'Past Month',
  'Past Quarter',
  'Past Year'
];

if (!API_KEY) {
  console.error("Error: API_KEY environment variable is required.");
  process.exit(1);
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

// Helper to get formatted date string (YYYY-MM-DD) in Central Time (CST/CDT)
const getCentralDateString = () => {
  return new Intl.DateTimeFormat('en-CA', { // en-CA standardizes to YYYY-MM-DD
    timeZone: 'America/Chicago',
    year: 'numeric',
    month: '2-digit',
    day: '2-digit'
  }).format(new Date());
};

const getDateRange = (timeFrame) => {
  const todayStr = new Date().toLocaleString("en-US", { timeZone: "America/Chicago" });
  const end = new Date(todayStr);
  const start = new Date(todayStr);

  switch (timeFrame) {
    case 'Past Day': start.setDate(end.getDate() - 1); break;
    case 'Past Week': start.setDate(end.getDate() - 7); break;
    case 'Past Month': start.setMonth(end.getMonth() - 1); break;
    case 'Past Quarter': start.setMonth(end.getMonth() - 3); break;
    case 'Past Year': start.setFullYear(end.getFullYear() - 1); break;
  }
  return `from ${start.toLocaleDateString()} to ${end.toLocaleDateString()}`;
};

const buildPrompt = (timeFrame) => {
  const dateRange = getDateRange(timeFrame);
  const isShortTerm = timeFrame === 'Past Day' || timeFrame === 'Past Week';

  const baseContext = `
    You are a Chief Audit Executive's AI assistant for a **Large Mutual Life Insurance and Wealth Management Company**.
    Target Audience: Internal Audit Planning Committee & Risk Committee.
    Date Range: ${dateRange} (${timeFrame}).

    Context: The company offers Life Insurance, Annuities, Disability Income, and Wealth Management/Investment products.
    Key Concerns: Solvency, Policyholder Protection, Regulatory Compliance (NAIC/SEC/DOL), Interest Rate Risk, and Digital Transformation.
  `;

  const specificInstructions = isShortTerm 
    ? `
      TASK: Search for specific, recent EVENTS that occurred strictly within this date range affecting the Insurance & Financial Services sector.
      
      LOOK FOR:
      - New regulatory enforcement actions (SEC, FINRA, State Insurance Depts) or fines.
      - Specific cyber breaches in financial services or third-party TPAs.
      - Sudden market shocks affecting asset management or yield curves.
      - Immediate operational disruptions or competitor scandals (e.g., sales practice violations).

      STYLE: News-brief style. Factual and immediate.
    `
    : `
      TASK: Analyze broad TRENDS and systemic shifts over this period relevant to Life Insurance & Wealth.
      
      LOOK FOR:
      - Evolving regulatory themes (e.g., DOL Fiduciary Rule, NAIC AI Model Bulletin, Privacy laws).
      - Emerging Actuarial/Underwriting risks (e.g., mortality trends, climate impact on health, genetic testing laws).
      - Macroeconomic shifts affecting investment income, annuities, and capital requirements.
      - Technology risks: AI bias in underwriting, legacy system modernization challenges.

      STYLE: Strategic analysis. Thematic and forward-looking.
    `;

  return `
    ${baseContext}
    ${specificInstructions}

    REQUIRED OUTPUT FORMAT (Markdown):
    For each risk found (limit to top 3-5), use this exact structure:

    ### [Risk Title]
    **Context**: [2-3 sentences explaining what happened or the trend]
    
    **Implications for Audit**:
    *   [Specific audit action: e.g., "Review model governance," "Test TPA controls," "Assess liquidity stress testing"]
    *   [Risk impact consideration]

    Constraints:
    - Do NOT be generic. 
    - Cite real entities, laws, or events found in search.
    - If no significant specific events occurred (for Day/Week), state "No major high-impact risk events detected" but provide 1 minor observation.
  `;
};

async function generateReport() {
  console.log("Starting AuditScout AI Headless Scan...");
  
  // Ensure report directory exists
  try {
    await fs.access(REPORT_DIR);
  } catch {
    await fs.mkdir(REPORT_DIR, { recursive: true });
  }

  // Use robust Central Time string
  const dateStr = getCentralDateString();
  
  let fullReport = `# Daily Emerging Risk Register\n\n`;
  fullReport += `**Date:** ${dateStr}\n`;
  fullReport += `**Model:** ${MODEL_NAME}\n`;
  fullReport += `**Generated By:** AuditScout AI (Automated Workflow)\n\n---\n\n`;

  for (const timeFrame of TIME_FRAMES) {
    console.log(`Scanning timeframe: ${timeFrame}...`);
    
    try {
      const response = await ai.models.generateContent({
        model: MODEL_NAME,
        contents: buildPrompt(timeFrame),
        config: {
          tools: [{ googleSearch: {} }],
          temperature: 0.2,
        },
      });

      const content = response.text || "No significant risks identified.";
      
      fullReport += `## ${timeFrame}\n\n`;
      fullReport += `${content}\n\n`;

      // Add sources if available
      const chunks = response.candidates?.[0]?.groundingMetadata?.groundingChunks || [];
      if (chunks.length > 0) {
        fullReport += `**Sources:**\n`;
        chunks.forEach(chunk => {
          if (chunk.web && chunk.web.uri) {
            fullReport += `- [${chunk.web.title || 'Source'}](${chunk.web.uri})\n`;
          }
        });
      }
      fullReport += `\n---\n\n`;
      
      // Rate limiting pause
      await new Promise(resolve => setTimeout(resolve, 2000));

    } catch (error) {
      console.error(`Error scanning ${timeFrame}:`, error.message);
      fullReport += `## ${timeFrame}\n\n*Error: Failed to generate scan for this timeframe.*\n\n---\n\n`;
    }
  }

  // Filename is explicitly date-based
  const filename = `risk-register-${dateStr}.md`;
  const filePath = path.join(REPORT_DIR, filename);
  
  await fs.writeFile(filePath, fullReport, 'utf-8');
  console.log(`Scan complete. Report saved to: ${filePath}`);
}

generateReport().catch(err => {
  console.error("Fatal Error:", err);
  process.exit(1);
});
